openapi: 3.1.0
info:
  title: Phonic
  description: The next-generation voice AI platform to build, observe, and evaluate your voice AI agents.
  license:
    name: MIT
  version: 1.0.0
servers:
  - url: https://api.phonic.co/v1
security:
  - bearerAuth: []
paths:
  /agents:
    get:
      description: Returns all agents in a project.
      parameters:
        - name: project
          in: query
          description: The name of the project to list agents for.
          required: false
          schema:
            type: string
            default: main
      responses:
        "200":
          description: Success response
          content:
            application/json:
              schema:
                type: object
                properties:
                  agents:
                    type: array
                    items:
                      $ref: "#/components/schemas/Agent"
                required:
                  - agents
              example:
                agents:
                  - $ref: "#/components/examples/AgentExample/value"
      x-codeSamples:
        - lang: typescript
          source: |
            import { Phonic } from "phonic";

            const phonic = new Phonic("ph_...");

            const agentsResult = await phonic.agents.list({
              project: "customer-support"
            });
        - lang: python
          source: |
            Coming soon
    post:
      description: Creates a new agent in a project.
      parameters:
        - name: project
          in: query
          description: The name of the project to create the agent in.
          required: false
          schema:
            type: string
            default: main
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateAgentRequest"
            example:
              name: support-agent
              phone_number: assign-automatically
              timezone: America/Los_Angeles
              voice_id: sarah
              welcome_message: Hi {{customer_name}}. How can I help you today?
              system_prompt: You are an expert in {{subject}}. Be friendly, helpful and concise.
              template_variables: {
                "customer_name": { "default_value": null },
                "subject": { "default_value": "Chess" }
              }
              tools: ["keypad_input"]
              boosted_keywords: ["Load ID", "dispatch"]
              no_input_poke_sec: 30
              no_input_poke_text: Are you still there?
              configuration_endpoint:
                url: https://api.example.com/config
                headers:
                  Authorization: Bearer token123
                timeout_ms: 7000
      responses:
        "200":
          description: Success response
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    description: The ID of the created agent.
                  name:
                    type: string
                    description: The name of the created agent.
                required:
                  - id
                  - name
              example:
                id: agent_12cf6e88-c254-4d3e-a149-a7f1bdd22783
                name: support-agent
      x-codeSamples:
        - lang: typescript
          source: |
            import { Phonic } from "phonic";

            const phonic = new Phonic("ph_...");

            const agent = await phonic.agents.create({
              project: "customer-support",
              name: "support-agent",
              phone_number: "assign-automatically",
              timezone: "America/Los_Angeles",
              voice_id: "sarah",
              welcome_message: "Hi {{customer_name}}. How can I help you today?",
              system_prompt: "You are an expert in {{subject}}. Be friendly, helpful and concise.",
              template_variables: {
                "customer_name": { "default_value": null },
                "subject": { "default_value": "Chess" }
              },
              tools: ["keypad_input"],
              boosted_keywords: ["Load ID", "dispatch"],
              no_input_poke_sec: 30,
              no_input_poke_text: "Are you still there?",
              configuration_endpoint: {
                url: "https://api.example.com/config",
                headers: {
                  Authorization: "Bearer token123"
                },
                timeout_ms: 7000
              }
            });
        - lang: python
          source: |
            Coming soon
  /agents/upsert:
    put:
      description: Upserts an agent by name. If an agent with the same name already exists, it will be updated. Otherwise, it will be created.
      parameters:
        - name: project
          in: query
          description: The name of the project containing the agent.
          required: false
          schema:
            type: string
            default: main
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpsertAgentRequest"
            example:
              name: support-agent
              phone_number: assign-automatically
              timezone: America/Los_Angeles
              voice_id: sarah
              welcome_message: Hi {{customer_name}}. How can I help you today?
              system_prompt: You are an expert in {{subject}}. Be friendly, helpful and concise.
              template_variables: {
                "customer_name": { "default_value": null },
                "subject": { "default_value": "Chess" }
              }
              tools: ["keypad_input"]
              boosted_keywords: ["Load ID", "dispatch"]
              no_input_poke_sec: 30
              no_input_poke_text: Are you still there?
              configuration_endpoint:
                url: https://api.example.com/config
                headers:
                  Authorization: Bearer token123
                timeout_ms: 7000
      responses:
        "200":
          description: Success response
          content:
            application/json:
              schema:
                type: object
                properties:
                  agent:
                    $ref: "#/components/schemas/Agent"
                  inserted:
                    type: boolean
                    description: Whether the agent was inserted.
                  updated:
                    type: boolean
                    description: Whether the agent was updated.
                required:
                  - agent
                  - inserted
                  - updated
              example:
                agent:
                  $ref: "#/components/examples/AgentExample/value"
                inserted: true
                updated: false
      x-codeSamples:
        - lang: typescript
          source: |
            import { Phonic } from "phonic";

            const phonic = new Phonic("ph_...");

            const agent = await phonic.agents.upsert({
              name: "support-agent",
              phone_number: "assign-automatically",
              timezone: "America/Los_Angeles",
              voice_id: "sarah",
              welcome_message: "Hi {{customer_name}}. How can I help you today?",
              system_prompt: "You are an expert in {{subject}}. Be friendly, helpful and concise.",
              template_variables: {
                "customer_name": { "default_value": null },
                "subject": { "default_value": "Chess" }
              },
              tools: ["keypad_input"],
              boosted_keywords: ["Load ID", "dispatch"],
              no_input_poke_sec: 30,
              no_input_poke_text: "Are you still there?",
              configuration_endpoint: {
                url: "https://api.example.com/config",
                headers: {
                  Authorization: "Bearer token123"
                },
                timeout_ms: 7000
              }
            });
        - lang: python
          source: |
            Coming soon
  /agents/{nameOrId}:
    get:
      description: Returns an agent by name or ID.
      parameters:
        - name: nameOrId
          in: path
          description: The name or the ID of the agent to get.
          required: true
          schema:
            type: string
        - name: project
          in: query
          description: The name of the project containing the agent. Only used when `nameOrId` is a name.
          required: false
          schema:
            type: string
            default: main
      responses:
        "200":
          description: Success response
          content:
            application/json:
              schema:
                type: object
                properties:
                  agent:
                    $ref: "#/components/schemas/Agent"
                required:
                  - agent
              example:
                agent:
                  $ref: "#/components/examples/AgentExample/value"
      x-codeSamples:
        - lang: typescript
          source: |
            import { Phonic } from "phonic";

            const phonic = new Phonic("ph_...");

            const agent = await phonic.agents.get("support-agent", {
              project: "customer-support"
            });
        - lang: python
          source: |
            Coming soon
    patch:
      description: Updates an agent by name or ID.
      parameters:
        - name: nameOrId
          in: path
          description: The name or the ID of the agent to update.
          required: true
          schema:
            type: string
        - name: project
          in: query
          description: The name of the project containing the agent. Only used when `nameOrId` is a name.
          required: false
          schema:
            type: string
            default: main
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateAgentRequest"
            example:
              name: support-agent
              phone_number: assign-automatically
              timezone: America/Los_Angeles
              voice_id: sarah
              welcome_message: Hi {{customer_name}}. How can I help you today?
              system_prompt: You are an expert in {{subject}}. Be friendly, helpful and concise.
              template_variables: {
                "customer_name": { "default_value": null },
                "subject": { "default_value": "Chess" }
              }
              tools: ["keypad_input"]
              boosted_keywords: ["Load ID", "dispatch"]
              no_input_poke_sec: 30
              no_input_poke_text: Are you still there?
              configuration_endpoint:
                url: https://api.example.com/config
                headers:
                  Authorization: Bearer token123
                timeout_ms: 7000
      responses:
        "200":
          description: Success response
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    description: Whether the agent was updated successfully.
                required:
                  - success
              example:
                success: true
      x-codeSamples:
        - lang: typescript
          source: |
            import { Phonic } from "phonic";

            const phonic = new Phonic("ph_...");

            const agent = await phonic.agents.update("support-agent", {
              name: "updated-support-agent",
              phone_number: "assign-automatically",
              timezone: "America/Los_Angeles",
              voice_id: "sarah",
              welcome_message: "Hi {{customer_name}}. How can I help you today?",
              system_prompt: "You are an expert in {{subject}}. Be friendly, helpful and concise.",
              template_variables: {
                "customer_name": { "default_value": null },
                "subject": { "default_value": "Chess" }
              },
              tools: ["keypad_input"],
              boosted_keywords: ["Load ID", "dispatch"],
              no_input_poke_sec: 30,
              no_input_poke_text: "Are you still there?",
              configuration_endpoint: {
                url: "https://api.example.com/config",
                headers: {
                  Authorization: "Bearer token123"
                },
                timeout_ms: 7000
              }
            });
        - lang: python
          source: |
            Coming soon
  /conversations/outbound_call:
    post:
      description: Initiates a call to a given phone number.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/OutboundCallRequest"
            example:
              to_phone_number: "+19189397081"
              config:
                agent: "support-agent"
                welcome_message: "Hi {{customer_name}}. How can I help you today?"
                system_prompt: "You are an expert in {{subject}}. Be friendly, helpful and concise."
                template_variables:
                  customer_name: "David"
                  subject: "Chess"
                voice_id: "sarah"
                no_input_poke_sec: 30
                no_input_poke_text: "Are you still there?"
                no_input_end_conversation_sec: 180
                boosted_keywords: ["Load ID", "dispatch"]
                tools: ["keypad_input"]
      responses:
        "200":
          description: Success response
          content:
            application/json:
              schema:
                type: object
                properties:
                  conversation_id:
                    type: string
                    description: The ID of the created conversation.
                required:
                  - conversation_id
              example:
                conversation_id: "conv_12cf6e88-c254-233e-a149-b2f1bdd22783"
      x-codeSamples:
        - lang: typescript
          source: |
            import { Phonic } from "phonic";

            const phonic = new Phonic("ph_...");

            const outboundCallResult = await phonic.conversations.outboundCall("+19189397081", {
              agent: "support-agent",
              // Optional overrides of agent settings
              welcome_message: "Hi {{customer_name}}. How can I help you today?",
              system_prompt: "You are an expert in {{subject}}. Be friendly, helpful and concise.",
              template_variables: {
                customer_name: "David",
                subject: "Chess"
              },
              voice_id: "sarah",
              no_input_poke_sec: 30,
              no_input_poke_text: "Are you still there?",
              no_input_end_conversation_sec: 180,
              boosted_keywords: ["Load ID", "dispatch"],
              tools: ["keypad_input"]
            });
        - lang: python
          source: |
            Coming soon
components:
  schemas:
    Agent:
      type: object
      properties:
        id:
          type: string
          description: The ID of the agent.
        name:
          type: string
          description: The name of the agent.
        phone_number:
          type: [string, "null"]
          description: The phone number that the agent uses to accept and initiate phone calls. `null` if the agent is not associated with a phone number, in which can the agent can be used via WebSockets.
        project:
          type: object
          description: The project the agent belongs to.
          properties:
            id:
              type: string
            name:
              type: string
          required:
            - id
            - name
        timezone:
          type: string
          description: The timezone of the agent. Used to format system variables like `{{system_time}}`.
          example: America/Los_Angeles
        voice_id:
          type: string
          description: The voice ID of the agent.
          example: sarah
        audio_format:
          type: string
          enum:
            - pcm_44100
            - mulaw_8000
          description: The audio format of the agent. If the agent has a phone number, the audio format will be `mulaw_8000`.
        welcome_message:
          type: [string, "null"]
          description: Message to play when the conversation starts.
        system_prompt:
          type: string
          description: Instructions for the conversation.
        template_variables:
          type: object
          additionalProperties:
            type: object
            properties:
              default_value:
                type: [string, "null"]
            required:
              - default_value
          description: Template variables that the agent can use in the welcome message and the system prompt.
          example:
            customer_name:
              default_value: null
            subject:
              default_value: Chess
        tools:
          type: array
          items:
            anyOf:
              - type: string
                enum:
                  - keypad_input
                  - natural_conversation_ending
                description: Built-in tool
              - type: string
                description: Custom tool
                example: send_email
          description: List of tools available to the agent.
        no_input_poke_sec:
          type: [integer, "null"]
          description: Number of seconds of silence before sending a poke message. `null` disables the poke message.
        no_input_poke_text:
          type: string
          description: The message to send after the specified silence.
        no_input_end_conversation_sec:
          type: integer
          description: Seconds of silence before ending the conversation.
        boosted_keywords:
          type: array
          items:
            type: string
          description: These words, or short phrases, will be more accurately recognized by the agent.
        configuration_endpoint:
          type: [object, "null"]
          properties:
            url:
              type: string
              example: https://api.example.com/config
            headers:
              type: object
              additionalProperties:
                type: string
              example:
                Authorization: Bearer token123
            timeout_ms:
              type: integer
              description: The timeout for the configuration endpoint in milliseconds.
          required:
            - url
            - headers
            - timeout_ms
          description: When not `null`, the agent will call this endpoint to get configuration options.
      required:
        - id
        - name
        - project
        - timezone
        - voice_id
        - audio_format
        - welcome_message
        - system_prompt
        - template_variables
        - tools
        - no_input_poke_sec
        - no_input_poke_text
        - no_input_end_conversation_sec
        - boosted_keywords
        - configuration_endpoint
        - phone_number
    CreateAgentRequest:
      type: object
      properties:
        name:
          type: string
          pattern: ^[a-z0-9-]+$
          description: The name of the agent. Can only contain lowercase letters, numbers and hyphens. Must be unique within the project.
          example: support-agent
        phone_number:
          oneOf:
            - type: string
              enum:
                - assign-automatically
            - type: "null"
          description: When set to `null`, the agent will not be associated with a phone number. When set to `"assign-automatically"`, the agent will be assigned a random phone number.
          default: "null"
        timezone:
          type: string
          description: The timezone of the agent. Used to format system variables like `{{system_time}}`.
          example: America/Los_Angeles
        voice_id:
          type: string
          description: The voice ID to use.
          default: grant
        audio_format:
          type: string
          enum:
            - pcm_44100
            - mulaw_8000
          description: The audio format of the agent.
          default: pcm_44100
        welcome_message:
          type: string
          description: Message to play when the conversation starts. Can contain template variables like `{{customer_name}}`.
          default: ""
          example: Hi {{customer_name}}. How can I help you today?
        system_prompt:
          type: string
          description: Instructions for the conversation. Can contain template variables like `{{subject}}`.
          default: Respond in 1-2 sentences.
          example: You are an expert in {{subject}}. Be friendly, helpful and concise.
        template_variables:
          type: object
          additionalProperties:
            type: object
            properties:
              default_value:
                type: [string, "null"]
            required:
              - default_value
          description: Variables that can be used in the welcome message and the system prompt.
          example:
            customer_name:
              default_value: null
            subject:
              default_value: Chess
        tools:
          type: array
          items:
            anyOf:
              - type: string
                enum:
                  - keypad_input
                  - natural_conversation_ending
                description: Built-in tool
              - type: string
                description: Custom tool
                example: send_email
          description: Array of built-in or custom tool names to use.
        no_input_poke_sec:
          type: [integer, "null"]
          description: Number of seconds of silence before sending a poke message. `null` disables the poke message.
          default: "null"
        no_input_poke_text:
          type: string
          description: The message to send after the specified silence.
          default: Are you still there?
        no_input_end_conversation_sec:
          type: integer
          description: Seconds of silence before ending the conversation.
          default: 180
        boosted_keywords:
          type: array
          items:
            type: string
          description: These words, or short phrases, will be more accurately recognized by the agent. 
          example: ["Load ID", "dispatch"]
        configuration_endpoint:
          type: [object, "null"]
          properties:
            url:
              type: string
              description: URL to call
            headers:
              type: object
              additionalProperties:
                type: string
              description: Object of key-value pairs.
              example:
                Authorization: Bearer token123
            timeout_ms:
              type: integer
              description: Timeout in milliseconds for the endpoint call.
              default: 3000
          required:
            - url
          description: When not `null`, at the beginning of the conversation the agent will make a POST request to this endpoint when to get configuration options.
          default: "null"
      required:
        - name
    UpdateAgentRequest:
      type: object
      properties:
        name:
          type: string
          pattern: ^[a-z0-9-]+$
          description: The name of the agent. Can only contain lowercase letters, numbers and hyphens. Must be unique within the project.
          example: support-agent
        phone_number:
          oneOf:
            - type: string
              enum:
                - assign-automatically
            - type: "null"
          description: When set to `null`, the agent will no longer be associated with a phone number. When set to `"assign-automatically"`, the agent will be assigned a random phone number. If the agent is already associated with a phone number, it will be assigned a new phone number.
          default: "null"
        timezone:
          type: string
          description: The timezone of the agent. Used to format system variables like `{{system_time}}`.
          example: America/Los_Angeles
        voice_id:
          type: string
          description: The voice ID to use.
          default: grant
        audio_format:
          type: string
          enum:
            - pcm_44100
            - mulaw_8000
          description: The audio format of the agent.
          default: pcm_44100
        welcome_message:
          type: string
          description: Message to play when the conversation starts. Can contain template variables like `{{customer_name}}`.
          default: ""
          example: Hi {{customer_name}}. How can I help you today?
        system_prompt:
          type: string
          description: Instructions for the conversation. Can contain template variables like `{{subject}}`.
          default: Respond in 1-2 sentences.
          example: You are an expert in {{subject}}. Be friendly, helpful and concise.
        template_variables:
          type: object
          additionalProperties:
            type: object
            properties:
              default_value:
                type: [string, "null"]
            required:
              - default_value
          description: Variables that can be used in the welcome message and the system prompt.
          example:
            customer_name:
              default_value: null
            subject:
              default_value: Chess
        tools:
          type: array
          items:
            anyOf:
              - type: string
                enum:
                  - keypad_input
                  - natural_conversation_ending
                description: Built-in tool
              - type: string
                description: Custom tool
                example: send_email
          description: Array of built-in or custom tool names to use.
        no_input_poke_sec:
          type: [integer, "null"]
          description: Number of seconds of silence before sending a poke message. `null` disables the poke message.
          default: "null"
        no_input_poke_text:
          type: string
          description: The message to send after the specified silence.
          default: Are you still there?
        no_input_end_conversation_sec:
          type: integer
          description: Seconds of silence before ending the conversation.
          default: 180
        boosted_keywords:
          type: array
          items:
            type: string
          description: These words, or short phrases, will be more accurately recognized by the agent. 
          example: ["Load ID", "dispatch"]
        configuration_endpoint:
          type: [object, "null"]
          properties:
            url:
              type: string
              description: URL to call
            headers:
              type: object
              additionalProperties:
                type: string
              description: Object of key-value pairs.
              example:
                Authorization: Bearer token123
            timeout_ms:
              type: integer
              description: Timeout in milliseconds for the endpoint call.
              default: 3000
          required:
            - url
          description: When not `null`, at the beginning of the conversation the agent will make a POST request to this endpoint when to get configuration options.
          default: "null"
    UpsertAgentRequest:
      type: object
      description: |
        The behavior differs based on whether the agent already exists:
        - For new agents: Default values apply.
        - For existing agents: Only provided fields are updated.
      properties:
        name:
          type: string
          pattern: ^[a-z0-9-]+$
          description: The name of the agent. Can only contain lowercase letters, numbers and hyphens. Must be unique within the project.
          example: support-agent
        phone_number:
          oneOf:
            - type: string
              enum:
                - assign-automatically
            - type: "null"
          description: When set to `null`, the agent will not (or no longer) be associated with a phone number. When set to `"assign-automatically"`, the agent will be assigned a random phone number. If the agent is already associated with a phone number, `"assign-automatically"` has no effect.
          default: "null"
        timezone:
          type: string
          description: The timezone of the agent. Used to format system variables like `{{system_time}}`.
          example: America/Los_Angeles
        voice_id:
          type: string
          description: The voice ID to use.
          default: grant
        audio_format:
          type: string
          enum:
            - pcm_44100
            - mulaw_8000
          description: The audio format of the agent.
          default: pcm_44100
        welcome_message:
          type: string
          description: Message to play when the conversation starts. Can contain template variables like `{{customer_name}}`.
          default: ""
          example: Hi {{customer_name}}. How can I help you today?
        system_prompt:
          type: string
          description: Instructions for the conversation. Can contain template variables like `{{subject}}`.
          default: Respond in 1-2 sentences.
          example: You are an expert in {{subject}}. Be friendly, helpful and concise.
        template_variables:
          type: object
          additionalProperties:
            type: object
            properties:
              default_value:
                type: [string, "null"]
            required:
              - default_value
          description: Variables that can be used in the welcome message and the system prompt.
          example:
            customer_name:
              default_value: null
            subject:
              default_value: Chess
        tools:
          type: array
          items:
            anyOf:
              - type: string
                enum:
                  - keypad_input
                  - natural_conversation_ending
                description: Built-in tool
              - type: string
                description: Custom tool
                example: send_email
          description: Array of built-in or custom tool names to use.
        no_input_poke_sec:
          type: [integer, "null"]
          description: Number of seconds of silence before sending a poke message. `null` disables the poke message.
          default: "null"
        no_input_poke_text:
          type: string
          description: The message to send after the specified silence.
          default: Are you still there?
        no_input_end_conversation_sec:
          type: integer
          description: Seconds of silence before ending the conversation.
          default: 180
        boosted_keywords:
          type: array
          items:
            type: string
          description: These words, or short phrases, will be more accurately recognized by the agent. 
          example: ["Load ID", "dispatch"]
        configuration_endpoint:
          type: [object, "null"]
          properties:
            url:
              type: string
              description: URL to call
            headers:
              type: object
              additionalProperties:
                type: string
              description: Object of key-value pairs.
              example:
                Authorization: Bearer token123
            timeout_ms:
              type: integer
              description: Timeout in milliseconds for the endpoint call.
              default: 3000
          required:
            - url
          description: When not `null`, at the beginning of the conversation the agent will make a POST request to this endpoint when to get configuration options.
          default: "null"
    OutboundCallRequest:
      type: object
      properties:
        to_phone_number:
          type: string
          description: The phone number to call in E.164 format.
          example: "+19189397081"
        config:
          $ref: "#/components/schemas/OutboundCallConfig"
      required:
        - to_phone_number
    OutboundCallConfig:
      type: object
      description: When an `agent` is provided, these `config` options override the agent settings.
      properties:
        agent:
          type: string
          description: The name of the agent to use for the call.
          example: "support-agent"
        project:
          type: string
          description: The name of the project to use for the call. Ignored when `agent` is provided.
          default: "main"
          example: "customer-support"
        welcome_message:
          type: [string, "null"]
          description: Message to play when the conversation starts. Can contain template variables like `{{customer_name}}`.
          default: "null"
          example: "Hi {{customer_name}}. How can I help you today?"
        system_prompt:
          type: string
          description: Instructions for the conversation. Can contain template variables like `{{subject}}`.
          default: Respond in 1-2 sentences.
          example: "You are an expert in {{subject}}. Be friendly, helpful and concise."
        template_variables:
          type: object
          additionalProperties:
            type: string
          description: Variables that can be used in the welcome message and the system prompt.
          example:
            customer_name: "David"
            subject: "Chess"
        voice_id:
          type: string
          description: The voice ID to use for the agent.
          default: "grant"
          example: "sarah"
        no_input_poke_sec:
          type: [integer, "null"]
          description: Number of seconds of silence before sending a poke message. `null` disables the poke message.
          default: "null"
        no_input_poke_text:
          type: string
          description: The message to send after the specified silence.
          default: Are you still there?
        no_input_end_conversation_sec:
          type: integer
          description: Seconds of silence before ending the conversation.
          default: 180
        boosted_keywords:
          type: array
          items:
            type: string
          description: These words, or short phrases, will be more accurately recognized by the agent.
          example: ["Load ID", "dispatch"]
        tools:
          type: array
          items:
            anyOf:
              - type: string
                enum:
                  - keypad_input
                  - natural_conversation_ending
                description: Built-in tool
              - type: string
                description: Custom tool
                example: send_email
          description: Array of built-in or custom tool names to use.
  examples:
    AgentExample:
      value:
        id: agent_12cf6e88-c254-4d3e-a149-a7f1bdd22783
        name: support-agent
        project:
          id: proj_ad0334f1-2487-4155-9df3-abd8129b29ad
          name: customer-support
        phone_number: "+1234567890"
        timezone: America/Los_Angeles
        voice_id: sarah
        audio_format: pcm_44100
        welcome_message: Hi {{customer_name}}. How can I help you today?
        system_prompt: You are an expert in {{subject}}. Be friendly, helpful and concise.
        template_variables:
          customer_name:
            default_value: null
          subject:
            default_value: Chess
        tools:
          - keypad_input
        no_input_poke_sec: 30
        no_input_poke_text: Are you still there?
        no_input_end_conversation_sec: 180
        boosted_keywords: ["Load ID", "dispatch"]
        configuration_endpoint:
          url: https://api.example.com/config
          headers:
            Authorization: Bearer token123
          timeout_ms: 7000
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      description: Bearer authentication header of the form `Bearer <PHONIC_API_KEY>`. Manage your API keys [here](https://phonic.co/api-keys).